spring:
  application:
    name: slovo
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      #- classpath:db/dev
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect